// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: hero.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "hero";

export interface HeroById {
  id: string;
}

export interface Hero {
  id: string;
  name: string;
  power: string;
  highlightedName: string;
  highlightedPower: string;
}

export interface HeroInput {
  name: string;
  power: string;
}

export interface SearchQuery {
  text: string;
}

export interface HeroList {
  heroes: Hero[];
}

export const HERO_PACKAGE_NAME = "hero";

export interface HeroServiceClient {
  findOne(request: HeroById): Observable<Hero>;

  search(request: SearchQuery): Observable<HeroList>;

  createHero(request: HeroInput): Observable<Hero>;
}

export interface HeroServiceController {
  findOne(request: HeroById): Promise<Hero> | Observable<Hero> | Hero;

  search(request: SearchQuery): Promise<HeroList> | Observable<HeroList> | HeroList;

  createHero(request: HeroInput): Promise<Hero> | Observable<Hero> | Hero;
}

export function HeroServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findOne", "search", "createHero"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("HeroService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("HeroService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const HERO_SERVICE_NAME = "HeroService";
